### PR TITLE
Pixel not equal

### PR DESCRIPTION
**Pull request by juananpe**
adds a pixelNotEqual assertion method and unit tests. I needed this method in a game, in order to test that a certain function draws a random colored-piece in a board from a set of certain pieces (I needed to test that the board has a certain color other than white at a specific position).

### CODE REVIEW

**Comment by JamesMGreene** [comment]
This didn't already exist? LOL, _whoops_... thanks for adding this, I'll try to get this merged and released later tonight or tomorrow. :+1:

**Comment by juananpe** [comment]
Great :+1: I have seen that TravisCI failed with Node.js 0.8 but not with 0.10. I don't really know why is it or whether my PR caused that (I doubt it, but you never know). It might be worth looking at it.

**Comment by JamesMGreene** [comment]
I noticed that as well but thanks for pointing it out. I'll be sure to look into it but I'll likely just remove 0.8 from the build matrix as it is probably a break in some devDependency... no worries.

**Comment by JamesMGreene** [comment]
Merged, updated, tagged, released, published, etc. as `v1.0.2`. Thanks! :+1:

**Comment by juananpe** [comment]
It has been a pleasure. I liked the idea/addition of the alias (pixelNotEqual / notPixelEqual).

**Comment by JamesMGreene** [comment]
Thanks. I know people have differing opinions on the wording of negative assertions so I thought I'd cover both bases. :wink:

**Pull request closed without merging**
